name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: divkix/reusable-workflows/.github/workflows/pre-commit.yml@main

  automerge-dependabot-pr:
    needs: pre-commit
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main

  heroku-push:
    # do not run if it is a pr
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v4 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          dontuseforce: 1
